"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Details",
      [
        {
          question_code: "01",
          options: "A",
          value_option: "Membaca instruksinya terlebih dahulu.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "01",
          options: "B",
          value_option:
            "Mendengarkan penjelasan dari orang lain yang pernah menggunakannya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "01",
          options: "C",
          value_option:
            "Langsung mencobanya begitu saja, saya bisa menemukan sendiri caranya selagi menggunakan.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "02",
          options: "A",
          value_option: "Melihat peta.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "02",
          options: "B",
          value_option: "Meminta petunjuk jalan secara lisan.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "02",
          options: "C",
          value_option: "Jalan begitu saja dan mungkin menggunakan kompas.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "03",
          options: "A",
          value_option: "Mengikuti resep tertulis.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "03",
          options: "B",
          value_option: "Menelepon teman untuk minta petunjuk.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "03",
          options: "C",
          value_option: "Mengikuti insting saja, mencoba-coba sambil memasak.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "04",
          options: "A",
          value_option: "Menuliskan instruksi untuknya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "04",
          options: "B",
          value_option: "Memberikan penjelasan lisan kepadanya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "04",
          options: "C",
          value_option:
            "Menunjukkan terlebih dahulu caranya, kemudian membiarkan dia mencoba sendiri.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "05",
          options: "A",
          value_option: "“Perhatikan yang saya lakukan!”",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "05",
          options: "B",
          value_option: "“Dengarkan penjelasan saya!”",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "05",
          options: "C",
          value_option: "“Cobalah sendiri!”",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "06",
          options: "A",
          value_option: "Mengunjungi museum dan galeri.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "06",
          options: "B",
          value_option: "Mendengarkan musik dan mengobrol dengan teman.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "06",
          options: "C",
          value_option: "Berolahraga atau membuat sesuatu sendiri.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "07",
          options: "A",
          value_option:
            "Membayangkan bagaimana terlihatnya ketika saya mengenakannya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "07",
          options: "B",
          value_option: "Membicarakannya dengan staff toko.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "07",
          options: "C",
          value_option: "Mencoba dan mencocokkannya langsung.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "08",
          options: "A",
          value_option: "Membaca banyak sekali brosur.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "08",
          options: "B",
          value_option: "Mendengarkan rekomendasi dari teman-teman.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "08",
          options: "C",
          value_option: "Membayangkan bagaimana rasanya berada di sana.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "09",
          options: "A",
          value_option: "Membaca ulasan di koran dan majalah.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "09",
          options: "B",
          value_option:
            "Mendiskusikan apa yang saya butuhkan dengan teman-teman saya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "09",
          options: "C",
          value_option: "Mencobai berbagai jenis mobil.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "10",
          options: "A",
          value_option: "Memperhatikan apa yang dilakukan oleh guru.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "10",
          options: "B",
          value_option:
            "Membicarakan setepat-tepatnya apa yang akan dilakukan dengan guru.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "10",
          options: "C",
          value_option:
            "Mencoba-coba dan menemukan sendiri yang harus saya lakukan.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "11",
          options: "A",
          value_option: "Membayangkan tampang hidangan tersebut.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "11",
          options: "B",
          value_option:
            "Membicarakan pilihan-pilihan yang ada dalam hati, atau dengan teman makan saya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "11",
          options: "C",
          value_option: "Membayangkan rasa dari makanan tersebut.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "12",
          options: "A",
          value_option: "Menontoni anggota band maupun para penonton lainnya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "12",
          options: "B",
          value_option: "Mendengarkan lirik dan irama lagu-lagunya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "12",
          options: "C",
          value_option: "Bergerak seirama musik tersebut.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "13",
          options: "A",
          value_option:
            "Memfokus pada kata atau gambar yang terpampang di hadapan saya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "13",
          options: "B",
          value_option:
            "Mendiskusikan permasalahan dan solusi yang mungkin dalam pikiran saya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "13",
          options: "C",
          value_option:
            "Banyak bergerak, memainkan pena, pensil dan barang-barang lainnya di dekat saya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "14",
          options: "A",
          value_option: "Warnanya dan tampangnya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "14",
          options: "B",
          value_option: "Gambaran yang diberikan penjualnya kepada saya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "14",
          options: "C",
          value_option: "Teksturnya dan bagaimana rasanya ketika saya sentuh.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "15",
          options: "A",
          value_option: "Melihat sesuatu.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "15",
          options: "B",
          value_option: "Diajak bicara.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "15",
          options: "C",
          value_option: "Melakukan sesuatu",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "16",
          options: "A",
          value_option: "Membayangkan skenario terburuk yang dapat terjadi.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "16",
          options: "B",
          value_option:
            "Membicarakan apa yang paling saya khawatirkan dalam hati.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "16",
          options: "C",
          value_option:
            "Tidak bisa diam, bergerak dan berjalan-jalan kian kemari.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "17",
          options: "A",
          value_option: "Penampilan mereka.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "17",
          options: "B",
          value_option: "Perkataan mereka terhadap saya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "17",
          options: "C",
          value_option: "Apa yang saya rasakan mengenai mereka.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "18",
          options: "A",
          value_option:
            "Menulis banyak sekali rangkuman dan diagram pelajaran.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "18",
          options: "B",
          value_option:
            "Membicarakan catatan saya, baik dengan diri sendiri (dalam hati) ataupun dengan orang lain.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "18",
          options: "C",
          value_option:
            "Membayangkan diri melakukan gerakan atau menulis kembali.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "19",
          options: "A",
          value_option: "Menunjukkan kepadanya apa yang saya maksud.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "19",
          options: "B",
          value_option:
            "Menerangkan kepada mereka dengan berbagai cara hingga ia paham.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "19",
          options: "C",
          value_option:
            "Mendorongnya untuk mencoba dan membicarakan ide saya tersebut dengannya ketika ia melaksanakannya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "20",
          options: "A",
          value_option:
            "Menonton film, fotografi, melihat karya seni rupa, atau melihati orang lewat.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "20",
          options: "B",
          value_option:
            "Mendengar musik dan radio, atau mengobrol dengan teman.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "20",
          options: "C",
          value_option:
            "Mengambil bagian dalam aktivitas olah raga, makan makanan enak, minum anggur nikmat, atau menari.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "21",
          options: "A",
          value_option: "Menonton TV.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "21",
          options: "B",
          value_option: "Mengobrol dengan teman.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "21",
          options: "C",
          value_option:
            "Melakukan aktivitas fisik atau membuat sesuatu barang.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "22",
          options: "A",
          value_option: "Mengatur agar bertemu langsung.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "22",
          options: "B",
          value_option: "Bicara di telepon dengannya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "22",
          options: "C",
          value_option:
            "Mencoba untuk bertemu sambil melakukan aktivitas lain, misalnya jalan-jalan atau makan-makan.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "23",
          options: "A",
          value_option: "Penampilan dan pakaiannya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "23",
          options: "B",
          value_option: "Suaranya dan suara yang dibuatnya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "23",
          options: "C",
          value_option: "Postur tubuh dan gerakannya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "24",
          options: "A",
          value_option:
            "Terus melihat kembali dalam pikiran saya hal yang membuat saya marah.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "24",
          options: "B",
          value_option:
            "Meninggikan suara dan memberitahukan perasaan saya kepada orang lain.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "24",
          options: "C",
          value_option:
            "Menghentakkan kaki, membanting pintu, atau menunjukkan kemarahan saya dengan cara fisik lainnya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "25",
          options: "A",
          value_option: "Wajah.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "25",
          options: "B",
          value_option: "Nama.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "25",
          options: "C",
          value_option: "Hal-hal yang pernah saya lakukan.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "26",
          options: "A",
          value_option: "Ia tidak mau menatap muka kita.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "26",
          options: "B",
          value_option: "Suaranya berubah ketika bicara dengan kita.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "26",
          options: "C",
          value_option: "Getaran nya pada kita berbeda.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "27",
          options: "A",
          value_option: "Saya mengatakan, “Saya senang bertemu kamu”",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "27",
          options: "B",
          value_option: "Saya mengatakan, “Saya senang mendengar tentang kamu”",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "27",
          options: "C",
          value_option: "Saya memeluknya atau menjabat tangannya.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "28",
          options: "A",
          value_option: "Menulis catatan atau menyimpan artikel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "28",
          options: "B",
          value_option:
            "Mengatakan atau mengulangi kata-kata dan kata kunci di kepala saya",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "28",
          options: "C",
          value_option:
            "Mempraktekan hal tersebut or membayangkan hal tersebut dilakukan ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "29",
          options: "A",
          value_option: "Menulis surat",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "29",
          options: "B",
          value_option: "Mengeluh lewat telepon",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "29",
          options: "C",
          value_option:
            "Mengembalikan barang tersebut ke toko atau mengeposkannya ke kantor pusat.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "30",
          options: "A",
          value_option: "Saya ngerti maksud Anda",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "30",
          options: "B",
          value_option: "Saya mendengarkan apa yang Anda jelaskan",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          question_code: "30",
          options: "C",
          value_option: "Saya mengerti perasaan Anda",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Details", null, {});
  },
};
